version: '3.2'

services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env.local
    ports:
      - ${MYSQL_PORT}:3306

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - server
    ports:
      - 4500:8080

  server:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    command: ["node", "./dist/main"]
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    env_file:
      - ./.env.local